-- Dining Record V4.0: personal wallets and atomic wallet settlement.
-- Run manually in the Supabase SQL Editor. This migration does not rewrite old records.

create table if not exists public.wallets (
  person text primary key,
  balance numeric(14,2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint wallets_person_check check (person in ('A','S','E','J','P'))
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  person text not null references public.wallets(person),
  type text not null,
  amount numeric(14,2) not null,
  balance_after numeric(14,2) not null,
  dining_record_id bigint null references public.dining_records(id) on delete set null,
  transfer_index integer null,
  transfer_from text null,
  transfer_to text null,
  note text null,
  reference_key text null,
  reverses_transaction_id bigint null references public.wallet_transactions(id) on delete restrict,
  constraint wallet_transactions_person_check check (person in ('A','S','E','J','P')),
  constraint wallet_transactions_type_check check (type in ('topup','settlement','adjustment','reversal')),
  constraint wallet_transactions_amount_check check (
    (type = 'topup' and amount > 0) or
    (type = 'settlement' and amount < 0) or
    (type = 'adjustment' and amount <> 0) or
    (type = 'reversal' and amount > 0)
  ),
  constraint wallet_transactions_transfer_index_check check (transfer_index is null or transfer_index >= 0)
);

create unique index if not exists wallet_transactions_reference_key_uidx
  on public.wallet_transactions(reference_key) where reference_key is not null;
create unique index if not exists wallet_transactions_one_reversal_uidx
  on public.wallet_transactions(reverses_transaction_id) where reverses_transaction_id is not null;
create index if not exists wallet_transactions_person_created_idx
  on public.wallet_transactions(person, created_at desc, id desc);
create index if not exists wallet_transactions_record_idx
  on public.wallet_transactions(dining_record_id) where dining_record_id is not null;

insert into public.wallets(person, balance)
values ('A',0),('S',0),('E',0),('J',0),('P',0)
on conflict (person) do nothing;

alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;

drop policy if exists "wallet balances readable" on public.wallets;
create policy "wallet balances readable" on public.wallets
  for select to anon, authenticated using (true);
drop policy if exists "wallet transactions authenticated read" on public.wallet_transactions;
create policy "wallet transactions authenticated read" on public.wallet_transactions
  for select to authenticated using (true);

create or replace function public.wallet_apply_change(
  p_person text,
  p_type text,
  p_amount numeric,
  p_note text,
  p_reference_key text
) returns public.wallet_transactions
language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_wallet public.wallets%rowtype;
  v_tx public.wallet_transactions%rowtype;
begin
  if auth.role() <> 'authenticated' then raise exception 'authentication required' using errcode='42501'; end if;
  if p_person not in ('A','S','E','J','P') then raise exception 'invalid wallet person'; end if;
  if p_type not in ('topup','adjustment') then raise exception 'invalid wallet operation'; end if;
  if p_amount is null or round(p_amount,2) <> p_amount or p_amount = 0 then raise exception 'amount must be a non-zero value with at most 2 decimals'; end if;
  if p_type = 'topup' and p_amount <= 0 then raise exception 'topup must be positive'; end if;
  if p_type = 'adjustment' and nullif(btrim(p_note),'') is null then raise exception 'adjustment note is required'; end if;
  if nullif(btrim(p_reference_key),'') is null then raise exception 'reference key is required'; end if;

  select * into v_tx from public.wallet_transactions where reference_key=p_reference_key;
  if found then
    if v_tx.person<>p_person or v_tx.type<>p_type or v_tx.amount<>p_amount then raise exception 'reference key conflict'; end if;
    return v_tx;
  end if;

  select * into v_wallet from public.wallets where person=p_person for update;
  if not found then raise exception 'wallet not found'; end if;
  update public.wallets set balance=balance+p_amount,updated_at=now() where person=p_person returning * into v_wallet;
  insert into public.wallet_transactions(person,type,amount,balance_after,note,reference_key)
  values(p_person,p_type,p_amount,v_wallet.balance,nullif(btrim(p_note),''),p_reference_key) returning * into v_tx;
  return v_tx;
exception when unique_violation then
  select * into v_tx from public.wallet_transactions where reference_key=p_reference_key;
  if found and v_tx.person=p_person and v_tx.type=p_type and v_tx.amount=p_amount then return v_tx; end if;
  raise;
end $$;

create or replace function public.settle_transfer_with_wallet(
  p_dining_record_id bigint,
  p_transfer_index integer,
  p_reference_key text
) returns jsonb
language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_record public.dining_records%rowtype; v_transfer jsonb; v_transfers jsonb;
  v_person text; v_to text; v_amount numeric(14,2); v_wallet public.wallets%rowtype;
  v_tx public.wallet_transactions%rowtype; v_status text; v_now timestamptz:=now();
begin
  if auth.role()<>'authenticated' then raise exception 'authentication required' using errcode='42501'; end if;
  if p_transfer_index is null or p_transfer_index<0 then raise exception 'invalid transfer index'; end if;
  if nullif(btrim(p_reference_key),'') is null then raise exception 'reference key is required'; end if;
  select * into v_tx from public.wallet_transactions where reference_key=p_reference_key;
  if found then return jsonb_build_object('already_processed',true,'transaction',to_jsonb(v_tx)); end if;

  select * into v_record from public.dining_records where id=p_dining_record_id for update;
  if not found then raise exception 'dining record not found'; end if;
  if jsonb_typeof(v_record.transfers)<>'array' or p_transfer_index>=jsonb_array_length(v_record.transfers) then raise exception 'transfer not found'; end if;
  v_transfer:=v_record.transfers->p_transfer_index; v_person:=v_transfer->>'from'; v_to:=v_transfer->>'to'; v_amount:=round((v_transfer->>'amount')::numeric,2);
  if v_person not in ('A','S','E','J','P') or v_to is null or v_amount<=0 then raise exception 'invalid transfer'; end if;
  if (v_transfer->>'settled')::boolean is true then raise exception 'transfer is already settled'; end if;

  select * into v_wallet from public.wallets where person=v_person for update;
  if not found then raise exception 'wallet not found'; end if;
  update public.wallets set balance=balance-v_amount,updated_at=v_now where person=v_person returning * into v_wallet;
  insert into public.wallet_transactions(person,type,amount,balance_after,dining_record_id,transfer_index,transfer_from,transfer_to,note,reference_key)
  values(v_person,'settlement',-v_amount,v_wallet.balance,p_dining_record_id,p_transfer_index,v_person,v_to,'餐費錢包結清',p_reference_key) returning * into v_tx;

  -- A first settlement also upgrades legacy transfers to explicit open state.
  select coalesce(jsonb_agg(case when x ? 'settled' then x else x||jsonb_build_object('settled',false,'settled_at',null,'settlement_method',null) end order by ord),'[]'::jsonb)
    into v_transfers from jsonb_array_elements(v_record.transfers) with ordinality a(x,ord);
  v_transfer:=v_transfer||jsonb_build_object('settled',true,'settled_at',v_now,'settlement_method','wallet','wallet_transaction_id',v_tx.id,'wallet_reference_key',p_reference_key);
  v_transfers:=jsonb_set(v_transfers,array[p_transfer_index::text],v_transfer,false);
  select case when count(*)=0 then 'not_required' when bool_and(coalesce((x->>'settled')::boolean,false)) then 'settled'
    when bool_or(coalesce((x->>'settled')::boolean,false)) then 'partial' else 'unsettled' end into v_status from jsonb_array_elements(v_transfers) x;
  update public.dining_records set transfers=v_transfers,settlement_status=v_status where id=p_dining_record_id;
  return jsonb_build_object('already_processed',false,'balance',v_wallet.balance,'transaction',to_jsonb(v_tx),'transfers',v_transfers,'settlement_status',v_status);
end $$;

create or replace function public.reverse_wallet_settlement(
  p_dining_record_id bigint,
  p_transfer_index integer,
  p_reference_key text
) returns jsonb
language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_record public.dining_records%rowtype; v_transfer jsonb; v_transfers jsonb;
  v_source public.wallet_transactions%rowtype; v_tx public.wallet_transactions%rowtype;
  v_wallet public.wallets%rowtype; v_status text;
begin
  if auth.role()<>'authenticated' then raise exception 'authentication required' using errcode='42501'; end if;
  if p_transfer_index is null or p_transfer_index<0 then raise exception 'invalid transfer index'; end if;
  if nullif(btrim(p_reference_key),'') is null then raise exception 'reference key is required'; end if;
  select * into v_tx from public.wallet_transactions where reference_key=p_reference_key;
  if found then return jsonb_build_object('already_processed',true,'transaction',to_jsonb(v_tx)); end if;
  select * into v_record from public.dining_records where id=p_dining_record_id for update;
  if not found then raise exception 'dining record not found'; end if;
  if jsonb_typeof(v_record.transfers)<>'array' or p_transfer_index>=jsonb_array_length(v_record.transfers) then raise exception 'transfer not found'; end if;
  v_transfer:=v_record.transfers->p_transfer_index;
  if v_transfer->>'settlement_method'<>'wallet' or coalesce((v_transfer->>'settled')::boolean,false) is not true then raise exception 'transfer is not wallet-settled'; end if;
  select * into v_source from public.wallet_transactions where id=(v_transfer->>'wallet_transaction_id')::bigint and type='settlement' for update;
  if not found then raise exception 'wallet settlement transaction not found'; end if;
  if exists(select 1 from public.wallet_transactions where reverses_transaction_id=v_source.id) then raise exception 'wallet settlement already reversed'; end if;
  select * into v_wallet from public.wallets where person=v_source.person for update;
  update public.wallets set balance=balance-v_source.amount,updated_at=now() where person=v_source.person returning * into v_wallet;
  insert into public.wallet_transactions(person,type,amount,balance_after,dining_record_id,transfer_index,transfer_from,transfer_to,note,reference_key,reverses_transaction_id)
  values(v_source.person,'reversal',-v_source.amount,v_wallet.balance,p_dining_record_id,p_transfer_index,v_source.transfer_from,v_source.transfer_to,'撤銷餐費錢包結清',p_reference_key,v_source.id) returning * into v_tx;
  v_transfer:=(v_transfer-'wallet_transaction_id'-'wallet_reference_key')||jsonb_build_object('settled',false,'settled_at',null,'settlement_method',null,'wallet_cycle',coalesce((v_transfer->>'wallet_cycle')::integer,0)+1);
  v_transfers:=jsonb_set(v_record.transfers,array[p_transfer_index::text],v_transfer,false);
  select case when count(*)=0 then 'not_required' when bool_and(coalesce((x->>'settled')::boolean,false)) then 'settled'
    when bool_or(coalesce((x->>'settled')::boolean,false)) then 'partial' else 'unsettled' end into v_status from jsonb_array_elements(v_transfers) x;
  update public.dining_records set transfers=v_transfers,settlement_status=v_status where id=p_dining_record_id;
  return jsonb_build_object('already_processed',false,'balance',v_wallet.balance,'transaction',to_jsonb(v_tx),'transfers',v_transfers,'settlement_status',v_status);
end $$;

revoke all on public.wallets, public.wallet_transactions from anon, authenticated;
grant select on public.wallets to anon, authenticated;
grant select on public.wallet_transactions to authenticated;
revoke all on function public.wallet_apply_change(text,text,numeric,text,text) from public, anon;
revoke all on function public.settle_transfer_with_wallet(bigint,integer,text) from public, anon;
revoke all on function public.reverse_wallet_settlement(bigint,integer,text) from public, anon;
grant execute on function public.wallet_apply_change(text,text,numeric,text,text) to authenticated;
grant execute on function public.settle_transfer_with_wallet(bigint,integer,text) to authenticated;
grant execute on function public.reverse_wallet_settlement(bigint,integer,text) to authenticated;
